### ISSUE TITLE
MempoolEntry Startup Error

### ISSUE THREAD

**Issue by jacohend** [bitcoinfees/feesim#3]
I am receiving this error shortly after startup. It appears to have originally been masked by closing the stdout/stderr channels. Any suggestions or further data I can provide to assist?

```panic: runtime error: integer divide by zero

goroutine 26 [running]:
github.com/bitcoinfees/feesim/collect/corerpc.(*MempoolEntry).FeeRate(0xc000425840, 0xc00008ae10)
	/home/ubuntu/src/github.com/bitcoinfees/feesim/collect/corerpc/data.go:28 +0x5c
github.com/bitcoinfees/feesim/collect.PruneLowFee(0xc00008ae10, 0x3e8)
	/home/ubuntu/src/github.com/bitcoinfees/feesim/collect/common.go:150 +0x355
github.com/bitcoinfees/feesim/collect/corerpc.Getters.func1(0xc000056b10, 0x1f1f3f8, 0xc3f320)
	/home/ubuntu/src/github.com/bitcoinfees/feesim/collect/corerpc/rpc.go:34 +0x166
main.loadCollectorConfig.func2(0x0, 0x0, 0x0)
	/home/ubuntu/src/github.com/chainpoint/feesim/main.go:275 +0xc9
main.(*FeeSim).Run(0xc00007b200, 0x0, 0x0)
	/home/ubuntu/src/github.com/chainpoint/feesim/feesim.go:106 +0x315
main.runFeeSim.func2(0xc000076840, 0xc00007b200)
	/home/ubuntu/src/github.com/chainpoint/feesim/main.go:203 +0x2b
created by main.runFeeSim
	/home/ubuntu/src/github.com/chainpoint/feesim/main.go:203 +0xf1e
	```

**Comment by bitcoinfees** [comment]
Hey there, unfortunately I don't really have time to maintain this project anymore. I really should update the Readme to reflect that.. Thanks for your interest in the project
